import { useState } from 'react';
import { Baby, Check, Heart, Mail, MapPin, Phone, School, Sparkles, Sun, Users } from 'lucide-react';
import { articles, programs } from '../data/content';
import { Link, useRouter } from '../lib/router';
import { ButtonLink, Doodles, PageHero, Photo, SectionTitle } from '../components/Shared';
import { Reveal } from '../components/ui/Reveal';
import { AboutSection, ActivitiesSection, AdmissionsSteps, BlogsSection, ClassesSection, DailySchedule, EnrollmentForm, EnrollmentSection, FAQSection, Hero, TeachersSection, TestimonialsSection, TourBanner, WhySection } from '../components/Sections';

export function HomePage() {
  return <><Hero /><AboutSection /><ClassesSection /><WhySection /><TourBanner /><ActivitiesSection /><TeachersSection /><TestimonialsSection /><FAQSection /><EnrollmentSection /><BlogsSection /></>;
}
export function AboutPage() {
  return <><PageHero title="About Young Explorers Academy" description="A caring community for the wonderful early years." /><AboutSection extended /><section className="section cream wave-section"><Doodles /><div className="container"><SectionTitle centered eyebrow="What Matters to Us" title="Small People. Big Possibilities." description="Our values shape the way we care, teach, and welcome every family." /><div className="values-grid">{[
    { Icon: Heart, title: 'Care Comes First', text: 'Children learn best when they feel safe, heard, and understood. We begin with warm relationships and take time to notice the little things.' },
    { Icon: Sparkles, title: 'Curiosity Leads the Way', text: 'Questions are the beginning of an adventure. We make room for imagination and help children discover answers through everyday experiences.' },
    { Icon: Users, title: 'We Grow Together', text: 'Families are an essential part of our school community. Open conversations and shared celebrations make the journey more meaningful.' },
  ].map(({ Icon, title, text }, i) => <Reveal className="value-card" delay={i * 90} key={title}><Icon /><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section><WhySection /><TeachersSection /><TourBanner /><TestimonialsSection /></>;
}
export function ClassesPage() { return <><PageHero title="Our Classes" description="The right little adventure for every age and stage." /><ClassesSection all /><WhySection /><TourBanner /><FAQSection /></>; }

export function ClassDetailsPage({ slug }: { slug: string }) {
  const program = programs.find(p => p.slug === slug);
  if (!program) return <NotFoundPage />;
  return <><PageHero title={program.title} parent={{ title: 'Classes', to: '/classes' }} description={program.description} /><section className="section"><div className="container detail-layout"><div className="detail-main"><Reveal><Photo className="detail-photo" src={program.image} alt={program.title} /><span className="eyebrow">Learning With a Little Wonder</span><h2>A Nurturing Space for Your Child to Grow</h2><p>{program.detail}</p><p>Every child brings their own interests, strengths, and pace. Our teachers observe, encourage, and adapt activities to make each day welcoming and meaningful.</p><h3>What We’ll Discover Together</h3><ul className="skills-list">{program.skills.map(skill => <li key={skill}><Check />{skill}</li>)}</ul><h3>Play With Purpose</h3><p>Our day balances child-led exploration with gentle guidance, shared stories, creative projects, movement, and rest. We make time for the joy of learning as well as the skills that prepare children for what comes next.</p><h3>Parents Are Part of the Journey</h3><p>We welcome your questions and insights. Everyday conversations help us understand your child and celebrate the progress you notice at home and in the classroom.</p></Reveal></div><aside className="detail-sidebar"><h3>Your Program at a Glance</h3><dl><div><dt>Age group</dt><dd>{program.age} years</dd></div><div><dt>Learning group</dt><dd>{program.students} children</dd></div><div><dt>Program</dt><dd>{program.category}</dd></div><div><dt>Days</dt><dd>Monday – Friday</dd></div><div><dt>Session</dt><dd>9:00 am – 12:00 pm</dd></div></dl><p className="price">${program.price}<small> / month</small></p><ButtonLink to={`/admissions?program=${program.slug}#enrollment`}>Enquire About This Class</ButtonLink><p>Talk to our team about availability and the best schedule for your family.</p></aside></div></section><DailySchedule /><TourBanner /><FAQSection /></>;
}
export function ActivitiesPage() { return <><PageHero title="Play, Create & Discover" description="A little imagination turns every day into an adventure." /><ActivitiesSection /><DailySchedule /><TourBanner /><EnrollmentSection /></>; }
export function AdmissionsPage() {
  const { location } = useRouter();
  const query = location.split('?')[1]?.split('#')[0] || '';
  const selected = new URLSearchParams(query).get('program') || '';
  const initialProgram = programs.some(p => p.slug === selected) ? selected : '';
  return <><PageHero title="Join the Young Explorers Academy Family" description="A warm welcome and a helping hand, from your first visit to the first day." /><AdmissionsSteps /><EnrollmentSection key={initialProgram} initialProgram={initialProgram} /><FAQSection /></>;
}
export function TeachersPage() { return <><PageHero title="Meet Our Teachers" description="Patient guides, big imaginations, and hearts full of care." /><TeachersSection page /><AboutSection /><TourBanner /></>; }
export function FAQsPage() { return <><PageHero title="Frequently Asked Questions" description="A little more about life, learning, and joining us at Young Explorers Academy." /><FAQSection full /><TourBanner /><EnrollmentSection /></>; }
export function BlogPage() { return <><PageHero title="Our Little Journal" description="Thoughts, ideas, and inspiration for the wonderful early years." /><BlogsSection archive /><TourBanner /></>; }

export function PricingPage() {
  const [yearly, setYearly] = useState(false);
  const plans = [
    { title: 'Little Beginnings', text: 'A gentle introduction to learning together.', price: 150, Icon: Baby, slug: 'early-learners', features: ['Morning learning sessions', 'Play-based activities', 'Creative arts and stories', 'Morning snack included', 'Family progress conversations'] },
    { title: 'Growing Explorers', text: 'A full day of discoveries and friendships.', price: 280, Icon: Sun, slug: 'preschool-foundations', features: ['Full-day learning and care', 'All morning activities', 'Lunch and afternoon snack', 'Outdoor play and exploration', 'Quiet time and cozy corners', 'Family progress conversations'] },
    { title: 'Ready for Adventure', text: 'A confident next step toward school.', price: 180, Icon: School, slug: 'pre-k-preparation', features: ['Pre-kindergarten sessions', 'Early literacy and numeracy', 'Small learning groups', 'Music, art, and movement', 'School-readiness activities'] },
  ];
  return <><PageHero title="Simple, Thoughtful Plans" description="Find a learning rhythm that works for your child and your family." /><section className="section"><div className="container"><SectionTitle centered eyebrow="Our Learning Plans" title="A Little Plan for a Bright Beginning" description="Choose the care and learning experience that feels right. Our team is happy to talk through the details." /><div className="pricing-toggle" aria-label="Billing period"><button className={!yearly ? 'selected' : ''} onClick={() => setYearly(false)} aria-pressed={!yearly}>Monthly</button><button className={yearly ? 'selected' : ''} onClick={() => setYearly(true)} aria-pressed={yearly}>Yearly <small>Save 10%</small></button></div><div className="pricing-grid">{plans.map(({ title, text, price, Icon, slug, features }, i) => <Reveal key={title} delay={i * 100}><article className={`pricing-card ${i === 1 ? 'featured' : ''}`}>{i === 1 && <span className="popular">A Family Favorite</span>}<Icon /><h3>{title}</h3><p>{text}</p><div className="plan-price" aria-live="polite"><strong>${yearly ? Math.round(price * 12 * .9).toLocaleString('en-US') : price}</strong><small> / {yearly ? 'year' : 'month'}</small></div><ul>{features.map(f => <li key={f}><Check />{f}</li>)}</ul><ButtonLink to={`/admissions?program=${slug}#enrollment`}>Explore This Plan</ButtonLink></article></Reveal>)}</div><p className="pricing-footnote">Speak with our team about available places, flexible schedules, and what is included before choosing your plan.</p></div></section><FAQSection /><TourBanner /></>;
}

export function BlogPostPage({ slug }: { slug: string }) {
  const article = articles.find(a => a.slug === slug);
  if (!article) return <NotFoundPage />;
  return <><PageHero title={article.title} parent={{ title: 'Our Journal', to: '/blog' }} /><section className="section"><div className="container article-layout"><article className="article-body"><Photo className="article-hero-photo" src={article.image} alt={article.title} /><p className="article-meta">{article.category} · {article.date} · {article.readTime}</p><p className="intro">{article.intro}</p>{article.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<div className="article-callout"><p>Every child’s journey is different. Follow their interests, make time to connect, and enjoy the small discoveries along the way.</p><ButtonLink to="/classes">Explore Our Learning Programs</ButtonLink></div><Link className="text-link" to="/blog">← Back to Our Journal</Link></article><aside className="article-sidebar"><h3>More Little Ideas</h3>{articles.filter(a => a.slug !== slug).map(a => <Link to={`/blog/${a.slug}`} key={a.slug}>{a.title}</Link>)}<h3 style={{ marginTop: 32 }}>Come Meet Us</h3><p>Discover a warm, playful start to your child’s learning journey.</p><ButtonLink className="sidebar-button" to="/admissions#enrollment">Book a Visit</ButtonLink></aside></div></section></>;
}

export function ContactPage() {
  return <><PageHero title="Let’s Say Hello" description="We are here to answer your questions and help your family feel at home." /><section className="section"><div className="container two-column contact-layout"><Reveal className="contact-copy"><span className="eyebrow">Get in Touch</span><h2>Every New Adventure Starts With a Conversation</h2><p>Wondering about a class, planning a visit, or simply curious about our school? We would love to hear from you.</p><div className="contact-cards"><div className="contact-card"><span className="round-icon"><MapPin /></span><div><h3>Come Visit</h3><p>123 Learning Lane,<br />Happy Kids City</p></div></div><div className="contact-card"><span className="round-icon"><Phone /></span><div><h3>Give Us a Call</h3><a href="tel:+12025550128">+1 (202) 555-0128</a></div></div><div className="contact-card"><span className="round-icon"><Mail /></span><div><h3>Send a Little Note</h3><a href="mailto:hello@young-explorers-academy.example">hello@young-explorers-academy.example</a></div></div><div className="contact-card"><span className="round-icon"><Sun /></span><div><h3>Our School Day</h3><p>Monday – Friday: 8:00 am – 5:00 pm<br />Saturday & Sunday: Closed</p></div></div></div><div className="contact-note">Planning your first visit? We will help you find a convenient time to meet our teachers and explore together.</div></Reveal><Reveal className="contact-form-surface"><EnrollmentForm contact /></Reveal></div></section><FAQSection /></>;
}

export function LegalPage({ privacy }: { privacy: boolean }) {
  return <><PageHero title={privacy ? 'Privacy Policy' : 'Terms & Conditions'} /><section className="section"><div className="container legal-content"><h2>About This Website Preview</h2><p>This Young Explorers Academy website is a design preview. The school profiles, names, testimonials, statistics, schedules, contact information, and prices are illustrative.</p><h2>{privacy ? 'Information You Enter' : 'Requests and Enrollment'}</h2><p>{privacy ? 'With the default project settings, form entries stay in your browser memory and are not sent to a server or saved in browser storage. If you choose to download a request, a text file is created on your device. Newsletter signup is also a preview and does not create a subscription.' : 'Completing a form in this preview does not book a visit, reserve a place, create a subscription, or enter into a contract. No payments are taken through this website.'}</p><h2>{privacy ? 'Website Assets' : 'Content and Availability'}</h2><p>{privacy ? 'Images and fonts are bundled with the project. The default site does not use analytics or advertising cookies. Contact links open your own phone or email application only when you choose to use them.' : 'The information shown here demonstrates the website design and should be replaced with the school’s confirmed details before use as a live service. Program availability and terms should be confirmed with the operating school.'}</p><h2>Questions</h2><p>For information about this project, consult its README. An operating school should publish its own reviewed privacy notice and terms when launching the site.</p><ButtonLink to="/" className="legal-home">Back to Young Explorers Academy</ButtonLink></div></section></>;
}
export function NotFoundPage() { return <section className="not-found"><Doodles /><div className="container"><p className="error-number" aria-hidden="true">404</p><span className="eyebrow">A Little Detour</span><h1 tabIndex={-1}>This Page Went Out to Play</h1><p>We couldn’t find that page. Let’s head back to a familiar place and try another adventure.</p><ButtonLink to="/">Back to Home</ButtonLink></div></section>; }
